export interface IContaminante {
  nivel2: string
  nivel3: string
  nivel4: string
  name: string
  value: number
  measureUnit: string
}

const walala: IContaminante[] = [
  {
    nivel2: 'Adquisición de electricidad',
    nivel3: 'Sistema Eléctrico de Aysén',
    nivel4: 'Sistema Eléctrico de Aysén',
    name: 'Dióxido de Carbono (CO2)',
    value: 0,
    measureUnit: 'kgCO2eq/MWh',
  },
  {
    nivel2: 'Adquisición de electricidad',
    nivel3: 'Sistema Eléctrico de Magallanes',
    nivel4: 'Sistema Eléctrico de Magallanes',
    name: 'Dióxido de Carbono (CO2)',
    value: 0,
    measureUnit: 'kgCO2eq/MWh',
  },
  {
    nivel2: 'Adquisición de electricidad',
    nivel3: 'Sistema Interconectado Central (SIC)',
    nivel4: 'Sistema Interconectado Central (SIC)',
    name: 'Dióxido de Carbono (CO2)',
    value: 405.6,
    measureUnit: 'kgCO2eq/MWh',
  },
  {
    nivel2: 'Adquisición de electricidad',
    nivel3: 'Sistema Interconectado del Norte Grande (SING)',
    nivel4: 'Sistema Interconectado del Norte Grande (SING)',
    name: '	Dióxido de Carbono (CO2)',
    value: 405.6,
    measureUnit: 'kgCO2eq/MWh',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Aire comprimido',
    nivel4: 'Gas licuado de petróleo',
    name: 'Dióxido de Carbono (CO2)',
    value: 1582.3485,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Aire comprimido',
    nivel4: 'Gas licuado de petróleo',
    name: 'Metano (CH4)',
    value: 0.7022,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Aire comprimido',
    nivel4: 'Gas licuado de petróleo',
    name: 'Óxido Nitroso (N2O)',
    value: 0.6645,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Aire comprimido',
    nivel4: 'Gas natural',
    name: 'Dióxido de Carbono (CO2)',
    value: 1.9746,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Aire comprimido',
    nivel4: 'Gas natural',
    name: 'Metano (CH4)',
    value: 0.001,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Aire comprimido',
    nivel4: 'Gas natural',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0009,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Aire comprimido',
    nivel4: 'Gasolina',
    name: 'Dióxido de Carbono (CO2)',
    value: 2253.6161,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Aire comprimido',
    nivel4: 'Gasolina',
    name: 'Metano (CH4)',
    value: 2.7317,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Aire comprimido',
    nivel4: 'Gasolina',
    name: 'Óxido Nitroso (N2O)',
    value: 5.1706,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Aire comprimido',
    nivel4: 'Petróleo 2 (Diésel)',
    name: 'Dióxido de Carbono (CO2)',
    value: 2698.5459,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Aire comprimido',
    nivel4: 'Petróleo 2 (Diésel)',
    name: '	Metano (CH4)',
    value: 3.0591,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Aire comprimido',
    nivel4: 'Petróleo 2 (Diésel)',
    name: 'Óxido Nitroso (N2O)',
    value: 5.7904,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Aire comprimido',
    nivel4: 'Petróleo 6',
    name: 'Dióxido de Carbono (CO2)',
    value: 3054.6952,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Aire comprimido',
    nivel4: 'Petróleo 6',
    name: 'Metano (CH4)',
    value: 3.3152,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Aire comprimido',
    nivel4: 'Petróleo 6',
    name: 'Óxido Nitroso (N2O)',
    value: 6.2751,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Calefacción',
    nivel4: 'Gas licuado de petróleo',
    name: 'Dióxido de Carbono (CO2)',
    value: 1582.3485,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Calefacción',
    nivel4: 'Gas licuado de petróleo',
    name: 'Metano (CH4)',
    value: 0.7022,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Calefacción',
    nivel4: 'Gas licuado de petróleo',
    name: 'Óxido Nitroso (N2O)',
    value: 0.6645,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Calefacción',
    nivel4: 'Gas natural',
    name: 'Dióxido de Carbono (CO2)',
    value: 1.9746,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Calefacción',
    nivel4: 'Gas natural',
    name: 'Metano (CH4)',
    value: 0.001,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Calefacción',
    nivel4: 'Gas natural',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0009,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Calefacción',
    nivel4: 'Gasolina',
    name: 'Dióxido de Carbono (CO2)',
    value: 2253.6161,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Calefacción',
    nivel4: 'Gasolina',
    name: 'Metano (CH4)',
    value: 2.7317,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Calefacción',
    nivel4: 'Gasolina',
    name: 'Óxido Nitroso (N2O)',
    value: 5.1706,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Calefacción',
    nivel4: 'Petróleo 2 (Diésel)',
    name: 'Metano (CH4)',
    value: 3.0591,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Calefacción',
    nivel4: 'Petróleo 2 (Diésel)',
    name: 'Óxido Nitroso (N2O)',
    value: 5.7904,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Calefacción',
    nivel4: 'Petróleo 2 (Diésel)',
    name: 'Dióxido de Carbono (CO2)',
    value: 2698.5459,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Calefacción',
    nivel4: 'Petróleo 6',
    name: 'Dióxido de Carbono (CO2)',
    value: 3054.6952,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Calefacción',
    nivel4: 'Petróleo 6',
    name: 'Metano (CH4)',
    value: 3.3152,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Calefacción',
    nivel4: 'Petróleo 6',
    name: 'Óxido Nitroso (N2O)',
    value: 6.2751,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Refrigeración',
    nivel4: 'Gas licuado de petróleo',
    name: 'Dióxido de Carbono (CO2)',
    value: 1582.3485,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Refrigeración',
    nivel4: 'Gas licuado de petróleo',
    name: 'Metano (CH4)',
    value: 0.7022,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Refrigeración',
    nivel4: 'Gas licuado de petróleo',
    name: 'Óxido Nitroso (N2O)',
    value: 0.6645,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Refrigeración',
    nivel4: 'Gas natural',
    name: 'Dióxido de Carbono (CO2)',
    value: 1.9746,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Refrigeración',
    nivel4: 'Gas natural',
    name: 'Metano (CH4)',
    value: 0.001,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Refrigeración',
    nivel4: 'Gas natural',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0009,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Refrigeración',
    nivel4: 'Gasolina',
    name: 'Óxido Nitroso (N2O)',
    value: 5.1706,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Refrigeración',
    nivel4: 'Gasolina',
    name: 'Metano (CH4)',
    value: 2.7317,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Refrigeración',
    nivel4: 'Gasolina',
    name: 'Dióxido de Carbono (CO2)',
    value: 2253.6161,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Refrigeración',
    nivel4: 'Petróleo 2 (Diésel)',
    name: 'Dióxido de Carbono (CO2)',
    value: 2698.5459,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Refrigeración',
    nivel4: 'Petróleo 2 (Diésel)',
    name: 'Metano (CH4)',
    value: 3.0591,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Refrigeración',
    nivel4: 'Petróleo 2 (Diésel)',
    name: 'Óxido Nitroso (N2O)',
    value: 5.7904,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Refrigeración',
    nivel4: 'Petróleo 6',
    name: 'Dióxido de Carbono (CO2)',
    value: 3054.6952,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Refrigeración',
    nivel4: 'Petróleo 6',
    name: 'Metano (CH4)',
    value: 3.3152,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Refrigeración',
    nivel4: 'Petróleo 6',
    name: 'Óxido Nitroso (N2O)',
    value: 6.2751,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Vapor',
    nivel4: 'Gas licuado de petróleo',
    name: 'Dióxido de Carbono (CO2)',
    value: 1582.3485,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Vapor',
    nivel4: 'Gas licuado de petróleo',
    name: 'Metano (CH4)',
    value: 0.7022,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Vapor',
    nivel4: 'Gas licuado de petróleo',
    name: 'Óxido Nitroso (N2O)',
    value: 0.6645,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Vapor',
    nivel4: 'Gas natural',
    name: 'Dióxido de Carbono (CO2)',
    value: 1.9746,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Vapor',
    nivel4: 'Gas natural',
    name: 'Metano (CH4)',
    value: 0.001,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Vapor',
    nivel4: 'Gas natural',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0009,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Vapor',
    nivel4: 'Gasolina',
    name: 'Dióxido de Carbono (CO2)',
    value: 2253.6161,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Vapor',
    nivel4: 'Gasolina',
    name: 'Metano (CH4)',
    value: 2.7317,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Vapor',
    nivel4: 'Gasolina',
    name: 'Óxido Nitroso (N2O)',
    value: 5.1706,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Vapor',
    nivel4: 'Petróleo 2 (Diésel)',
    name: 'Dióxido de Carbono (CO2)',
    value: 2698.5459,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Vapor',
    nivel4: 'Petróleo 2 (Diésel)',
    name: 'Metano (CH4)',
    value: 3.0591,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Vapor',
    nivel4: 'Petróleo 2 (Diésel)',
    name: 'Óxido Nitroso (N2O)',
    value: 5.7904,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Vapor',
    nivel4: 'Petróleo 6',
    name: 'Dióxido de Carbono (CO2)',
    value: 3054.6952,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Vapor',
    nivel4: 'Petróleo 6',
    name: 'Metano (CH4)',
    value: 3.3152,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2:
      'Adquisición de vapor, calefacción, refrigeración y aire comprimido',
    nivel3: 'Vapor',
    nivel4: 'Petróleo 6',
    name: 'Óxido Nitroso (N2O)',
    value: 6.2751,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2: 'Pérdidas por transmisión y distribución',
    nivel3: 'Sistema Eléctrico de Aysén',
    nivel4: 'Sistema Eléctrico de Aysén',
    name: 'Dióxido de Carbono (CO2)',
    value: 0,
    measureUnit: 'kgCO2eq/MWh',
  },
  {
    nivel2: 'Pérdidas por transmisión y distribución',
    nivel3: 'Sistema Eléctrico de Magallanes',
    nivel4: 'Sistema Eléctrico de Magallanes',
    name: 'Dióxido de Carbono (CO2)',
    value: 0,
    measureUnit: 'kgCO2eq/MWh',
  },
  {
    nivel2: 'Pérdidas por transmisión y distribución',
    nivel3: 'Sistema Interconectado Central (SIC)',
    nivel4: 'Sistema Interconectado Central (SIC)',
    name: 'Dióxido de Carbono (CO2)',
    value: 19.55,
    measureUnit: 'kgCO2eq/MWh',
  },
  {
    nivel2: 'Pérdidas por transmisión y distribución',
    nivel3: 'Sistema Interconectado del Norte Grande (SING)',
    nivel4: 'Sistema Interconectado del Norte Grande (SING)',
    name: 'Dióxido de Carbono (CO2)',
    value: 40.3,
    measureUnit: 'kgCO2eq/MWh',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Acero general',
    name: 'Dióxido de Carbono (CO2)',
    value: 2.75,
    measureUnit: 'kgCO2eq/kg',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Acero reciclado',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.43,
    measureUnit: 'kgCO2eq/kg',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Aluminio',
    name: 'Dióxido de Carbono (CO2)',
    value: 9.16,
    measureUnit: 'kgCO2eq/kg',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Fertilizante: fosfatados',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.3394,
    measureUnit: 'kgCO2eq/kg',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Fertilizante: Nitrato amonio',
    name: 'Dióxido de Carbono (CO2)',
    value: 2.313,
    measureUnit: 'kgCO2eq/kg',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Fertilizante: nitrogenados convencional',
    name: 'Dióxido de Carbono (CO2)',
    value: 1.7583,
    measureUnit: 'kgCO2eq/kg',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Fertilizante: NPK general',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.5441,
    measureUnit: 'kgCO2eq/kg',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Fertilizante: Urea',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.71,
    measureUnit: 'kgCO2eq/kg',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Gas licuado de petróleo',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.1892,
    measureUnit: 'kgCO2eq/l',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Gas natural',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.2755,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Gasolina',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.5575,
    measureUnit: 'kgCO2eq/l',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Hormigón',
    name: 'Dióxido de Carbono (CO2)',
    value: 134.8,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Impresión y publicación',
    name: 'Dióxido de Carbono (CO2)',
    value: 939,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Leña',
    name: 'Dióxido de Carbono (CO2)',
    value: 52.14,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Lubricantes',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.3397,
    measureUnit: 'kgCO2eq/l',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Madera y productos de madera',
    name: 'Dióxido de Carbono (CO2)',
    value: 435,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Metal: latas de aluminio y otros metales',
    name: 'Dióxido de Carbono (CO2)',
    value: 6519,
    measureUnit: 'kgCO2eq/kg',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Neumáticos',
    name: 'Dióxido de Carbono (CO2)',
    value: 3410,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Papel',
    name: 'Dióxido de Carbono (CO2)',
    value: 939,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Petróleo 2 (Diesel)',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.5543,
    measureUnit: 'kgCO2eq/l',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Plásticos: Plástico film promedio',
    name: 'Dióxido de Carbono (CO2)',
    value: 2590,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Plásticos: Policloruro de vinilo (PVC)',
    name: 'Dióxido de Carbono (CO2)',
    value: 3430,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Plásticos: Poliestireno (PS)',
    name: 'Dióxido de Carbono (CO2)',
    value: 3795,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Plásticos: Polietileno de alta densidad (HDPE)',
    name: 'Dióxido de Carbono (CO2)',
    value: 3194,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Plásticos: Polietileno de baja densidad (LDPE) y LLDPE',
    name: 'Dióxido de Carbono (CO2)',
    value: 2617,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Plásticos: Polipropileno (PP)',
    name: 'Dióxido de Carbono (CO2)',
    value: 3089,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Plásticos: Promedio',
    name: 'Dióxido de Carbono (CO2)',
    value: 3342,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Plásticos: Rígido promedio',
    name: 'Dióxido de Carbono (CO2)',
    value: 3199,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Plásticos: Teraftalato de Polietileno (PET)',
    name: 'Dióxido de Carbono (CO2)',
    value: 4070,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Productos alimenticios y bebidas general',
    name: 'Dióxido de Carbono (CO2)',
    value: 4060,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Textiles',
    name: 'Dióxido de Carbono (CO2)',
    value: 22310,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Tintas de impresión',
    name: 'Dióxido de Carbono (CO2)',
    value: 44423.4526,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Vidrio y productos de vidrio',
    name: 'Dióxido de Carbono (CO2)',
    value: 894.6,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Bienes adquiridos',
    nivel4: 'Yeso cartón',
    name: 'Dióxido de Carbono (CO2)',
    value: 120.1,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Servicios adquiridos',
    nivel4: 'Actividades legales, de negocios y consultorías',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.0004,
    measureUnit: 'kgCO2eq/$',
  },
  {
    nivel2: 'Bienes y servicios adquiridos',
    nivel3: 'Servicios adquiridos',
    nivel4: 'Agua potable: Suministro y tratamiento',
    name: 'Dióxido de Carbono (CO2)',
    value: 1.052,
    measureUnit: 'kgCO2eq/m3',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Aéreo - Avión trayecto doméstico (Chile continental)',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0014,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Aéreo - Avión trayecto doméstico (Chile continental)',
    name: 'Metano (CH4)',
    value: 0.0001,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Aéreo - Avión trayecto internacional (promedio)',
    name: 'Metano (CH4)',
    value: 0,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Aéreo - Avión trayecto doméstico (Chile continental)',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.2772,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Aéreo - Avión trayecto internacional (promedio)',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0009,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Aéreo - Avión trayecto internacional (promedio)',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.1781,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Bicicleta/A pie',
    name: 'Dióxido de Carbono (CO2)',
    value: 0,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Bicicleta/A pie',
    name: 'Metano (CH4)',
    value: 0,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Bicicleta/A pie',
    name: 'Óxido Nitroso (N2O)',
    value: 0,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Terrestre - Bus interurbano (aprox. 45 pers.)',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.012,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Terrestre - Bus interurbano (aprox. 45 pers.)',
    name: 'Metano (CH4)',
    value: 0,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Terrestre - Bus interurbano (aprox. 45 pers.)',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0002,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Terrestre - Bus local (aprox. 25 pers.)',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.027,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Terrestre - Bus local (aprox. 25 pers.)',
    name: 'Metano (CH4)',
    value: 0,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Terrestre - Bus local (aprox. 25 pers.)',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0004,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Terrestre - Bus transantiago',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.0386,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Terrestre - Bus transantiago',
    name: 'Metano (CH4)',
    value: 0.0001,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Terrestre - Bus transantiago',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0005,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Terrestre - Metro',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.033,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Terrestre - Metro',
    name: 'Metano (CH4)',
    value: 0,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Terrestre - Metro',
    name: 'Óxido Nitroso (N2O)',
    value: 0,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Terrestre - Motocicleta',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.0901,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Terrestre - Motocicleta',
    name: 'Metano (CH4)',
    value: 0.0001,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Terrestre - Motocicleta',
    name: 'Óxido Nitroso (N2O)',
    value: 0.002,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Terrestre - Taxi',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.2049,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Terrestre - Taxi',
    name: 'Metano (CH4)',
    value: 0.0003,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Terrestre - Taxi',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0045,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Terrestre - Tren',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.0485,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Terrestre - Tren',
    name: 'Metano (CH4)',
    value: 0.0001,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Terrestre - Tren',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0004,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Terrestre - Van',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.0428,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Terrestre - Van',
    name: 'Metano (CH4)',
    value: 0.0001,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Terrestre - Van',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0006,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Terrestre - Vehículo particular - Diesel',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0034,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Terrestre - Vehículo particular - Diesel',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.2453,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Terrestre - Vehículo particular - Diesel',
    name: 'Metano (CH4)',
    value: 0.0004,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Terrestre - Vehículo particular - Gasolina',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.2049,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Terrestre - Vehículo particular - Gasolina',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0045,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Transporte de clientes y visitantes',
    nivel4: 'Terrestre - Vehículo particular - Gasolina',
    name: 'Metano (CH4)',
    value: 0.0003,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Bicicleta/A pie',
    name: 'Dióxido de Carbono (CO2)',
    value: 0,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Bicicleta/A pie',
    name: 'Metano (CH4)',
    value: 0,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Bicicleta/A pie',
    name: 'Óxido Nitroso (N2O)',
    value: 0,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Bus interurbano (aprox. 45 pers.)',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.012,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Bus interurbano (aprox. 45 pers.)',
    name: 'Metano (CH4)',
    value: 0,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Bus interurbano (aprox. 45 pers.)',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0002,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Bus local (aprox. 25 pers.)',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.027,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Bus local (aprox. 25 pers.)',
    name: 'Metano (CH4)',
    value: 0,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Bus local (aprox. 25 pers.)',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0004,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Bus transantiago',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.0386,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Bus transantiago',
    name: 'Metano (CH4)',
    value: 0.0001,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Bus transantiago',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0005,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Colectivo',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.0512,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Colectivo',
    name: 'Metano (CH4)',
    value: 0.0001,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Colectivo',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0011,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Metro',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.033,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Metro',
    name: 'Metano (CH4)',
    value: 0,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Metro',
    name: 'Óxido Nitroso (N2O)',
    value: 0,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Metrotren',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.0533,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Metrotren',
    name: 'Metano (CH4)',
    value: 0.0001,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Metrotren',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0003,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Motocicleta',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.0901,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Motocicleta',
    name: 'Metano (CH4)',
    value: 0.0001,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Motocicleta',
    name: 'Óxido Nitroso (N2O)',
    value: 0.002,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Taxi',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.2049,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Taxi',
    name: 'Metano (CH4)',
    value: 0.0003,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Taxi',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0045,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Vehículo particular - diesel',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.2453,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Vehículo particular - diesel',
    name: 'Metano (CH4)',
    value: 0.0004,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Vehículo particular - diesel',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0034,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Vehículo particular - gasolina	',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.2049,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Vehículo particular - gasolina',
    name: 'Metano (CH4)',
    value: 0.0003,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Traslado diario de personal',
    nivel4: 'Vehículo particular - gasolina',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0045,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Aéreo - Avión trayecto doméstico (Chile continental)',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.2772,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Aéreo - Avión trayecto doméstico (Chile continental)',
    name: 'Metano (CH4)',
    value: 0.0001,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Aéreo - Avión trayecto doméstico (Chile continental)',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0014,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Aéreo - Avión trayecto internacional (promedio)',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.1781,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Aéreo - Avión trayecto internacional (promedio)',
    name: 'Metano (CH4)',
    value: 0,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Aéreo - Avión trayecto internacional (promedio)',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0009,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Terrestre - Bus interurbano (aprox. 45 pers.)',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.012,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Terrestre - Bus interurbano (aprox. 45 pers.)',
    name: 'Metano (CH4)',
    value: 0,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Terrestre - Bus interurbano (aprox. 45 pers.)',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0002,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Terrestre - Bus local (aprox. 25 pers.)',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.027,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Terrestre - Bus local (aprox. 25 pers.)',
    name: 'Metano (CH4)',
    value: 0,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Terrestre - Bus local (aprox. 25 pers.)',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0004,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Terrestre - Bus transantiago',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.0386,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Terrestre - Bus transantiago',
    name: 'Metano (CH4)',
    value: 0.0001,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Terrestre - Bus transantiago',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0005,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Terrestre - Metro',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.033,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Terrestre - Metro',
    name: 'Metano (CH4)',
    value: 0,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Terrestre - Metro',
    name: 'Óxido Nitroso (N2O)',
    value: 0,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Terrestre - Motocicleta',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.0901,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Terrestre - Motocicleta',
    name: 'Metano (CH4)',
    value: 0.0001,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Terrestre - Motocicleta',
    name: 'Óxido Nitroso (N2O)',
    value: 0.002,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Terrestre - Taxi',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.2049,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Terrestre - Taxi',
    name: 'Metano (CH4)',
    value: 0.0003,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Terrestre - Taxi',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0045,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Terrestre - Tren',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.0485,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Terrestre - Tren',
    name: 'Metano (CH4)',
    value: 0.0001,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Terrestre - Tren',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0004,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Terrestre - Van',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.0428,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Terrestre - Van',
    name: 'Metano (CH4)',
    value: 0.0001,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Terrestre - Van',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0006,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Terrestre - Vehículo particular - Diesel',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.2453,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Terrestre - Vehículo particular - Diesel',
    name: 'Metano (CH4)',
    value: 0.0004,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Terrestre - Vehículo particular - Diesel',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0034,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Terrestre - Vehículo particular - Gasolina',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.2049,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Terrestre - Vehículo particular - Gasolina',
    name: 'Metano (CH4)',
    value: 0.0003,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Movilización de personas',
    nivel3: 'Viajes de negocios',
    nivel4: 'Terrestre - Vehículo particular - Gasolina',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0045,
    measureUnit: 'kgCO2eq/persona-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Insumos - aéreos',
    nivel4: 'Aéreo - Avión trayecto doméstico (Chile continental)',
    name: 'Metano (CH4)',
    value: 0.0013,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Insumos - aéreos',
    nivel4: 'Aéreo - Avión trayecto doméstico (Chile continental)',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0247,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Insumos - aéreos',
    nivel4: 'Aéreo - Avión trayecto doméstico (Chile continental)',
    name: 'Dióxido de Carbono (CO2)',
    value: 4.9556,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Insumos - aéreos',
    nivel4: 'Aéreo - Avión trayecto internacional (promedio)',
    name: 'Dióxido de Carbono (CO2)',
    value: 1.4041,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Insumos - aéreos',
    nivel4: 'Aéreo - Avión trayecto internacional (promedio)',
    name: 'Metano (CH4)',
    value: 0.0001,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Insumos - aéreos',
    nivel4: 'Aéreo - Avión trayecto internacional (promedio)',
    name: 'Óxido Nitroso (N2O)',
    value: 0.007,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Insumos - marítimo',
    nivel4: 'Barco - a granel',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.0035,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Insumos - marítimo',
    nivel4: 'Barco - a granel',
    name: 'Metano (CH4)',
    value: 0,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Insumos - marítimo',
    nivel4: 'Barco - a granel',
    name: 'Óxido Nitroso (N2O)',
    value: 0,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Insumos - marítimo',
    nivel4: 'Barco - contenedor',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.0159,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Insumos - marítimo',
    nivel4: 'Barco - contenedor',
    name: 'Metano (CH4)',
    value: 0,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Insumos - marítimo',
    nivel4: 'Barco - contenedor',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0001,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Insumos - terrestre',
    nivel4: 'Camión articulado promedio carga 11 t',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.0855,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Insumos - terrestre',
    nivel4: 'Camión articulado promedio carga 11 t',
    name: 'Metano (CH4)',
    value: 0,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Insumos - terrestre',
    nivel4: 'Camión articulado promedio carga 11 t',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0012,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Insumos - terrestre',
    nivel4: 'Camión refrigerado promedio carga 7 t',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.1322,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Insumos - terrestre',
    nivel4: 'Camión refrigerado promedio carga 7 t',
    name: 'Metano (CH4)',
    value: 0.0001,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Insumos - terrestre',
    nivel4: 'Camión refrigerado promedio carga 7 t',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0018,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Insumos - terrestre',
    nivel4: 'Camión rígido promedio carga promedio 3 t',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.2074,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Insumos - terrestre',
    nivel4: 'Camión rígido promedio carga promedio 3 t',
    name: 'Metano (CH4)',
    value: 0.0001,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Insumos - terrestre',
    nivel4: 'Camión rígido promedio carga promedio 3 t',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0017,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Insumos - terrestre',
    nivel4: 'Tren',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.0292,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Insumos - terrestre',
    nivel4: 'Tren',
    name: 'Metano (CH4)',
    value: 0,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Insumos - terrestre',
    nivel4: 'Tren',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0003,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Insumos - terrestre',
    nivel4: 'Vehículos medianos (van) - diesel',
    name: 'Metano (CH4)',
    value: 0,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Insumos - terrestre',
    nivel4: 'Vehículos medianos (van) - diesel',
    name: 'Óxido Nitroso (N2O)',
    value: 0.004,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Insumos - terrestre',
    nivel4: 'Vehículos medianos (van) - diesel',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.5595,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Productos - aéreos',
    nivel4: 'Aéreo - Avión trayecto doméstico (Chile continental)',
    name: 'Dióxido de Carbono (CO2)',
    value: 4.9556,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Productos - aéreos',
    nivel4: 'Aéreo - Avión trayecto doméstico (Chile continental)',
    name: 'Metano (CH4)',
    value: 0.0013,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Productos - aéreos',
    nivel4: 'Aéreo - Avión trayecto doméstico (Chile continental)',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0247,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Productos - aéreos',
    nivel4: 'Aéreo - Avión trayecto internacional (promedio)',
    name: 'Dióxido de Carbono (CO2)',
    value: 1.4041,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Productos - aéreos',
    nivel4: 'Aéreo - Avión trayecto internacional (promedio)',
    name: 'Metano (CH4)',
    value: 0.0001,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Productos - aéreos',
    nivel4: 'Aéreo - Avión trayecto internacional (promedio)',
    name: 'Óxido Nitroso (N2O)',
    value: 0.007,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Productos - marítimo',
    nivel4: 'Barco - a granel',
    name: 'Óxido Nitroso (N2O)',
    value: 0,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Productos - marítimo',
    nivel4: 'Barco - a granel',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.0035,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Productos - marítimo',
    nivel4: 'Barco - a granel',
    name: 'Metano (CH4)',
    value: 0,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Productos - marítimo',
    nivel4: 'Barco - contenedor',
    name: 'Metano (CH4)',
    value: 0,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Productos - marítimo',
    nivel4: 'Barco - contenedor',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0001,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Productos - marítimo',
    nivel4: 'Barco - contenedor',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.0159,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Productos - terrestre',
    nivel4: 'Camión articulado promedio carga 11 t',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.0855,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Productos - terrestre',
    nivel4: 'Camión articulado promedio carga 11 t',
    name: 'Metano (CH4)',
    value: 0,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Productos - terrestre',
    nivel4: 'Camión articulado promedio carga 11 t',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0012,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Productos - terrestre',
    nivel4: 'Camión refrigerado promedio carga 7 t',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.1322,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Productos - terrestre',
    nivel4: 'Camión refrigerado promedio carga 7 t',
    name: 'Metano (CH4)',
    value: 0.0001,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Productos - terrestre',
    nivel4: 'Camión refrigerado promedio carga 7 t',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0018,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Productos - terrestre',
    nivel4: 'Camión rígido promedio carga promedio 3 t',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.2074,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Productos - terrestre',
    nivel4: 'Camión rígido promedio carga promedio 3 t',
    name: 'Metano (CH4)',
    value: 0.0001,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Productos - terrestre',
    nivel4: 'Camión rígido promedio carga promedio 3 t',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0017,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Productos - terrestre',
    nivel4: 'Tren',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.0292,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Productos - terrestre',
    nivel4: 'Tren',
    name: 'Metano (CH4)',
    value: 0,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Productos - terrestre',
    nivel4: 'Tren',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0003,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Productos - terrestre',
    nivel4: 'Vehículos medianos (van) - diesel',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.5595,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Productos - terrestre',
    nivel4: 'Vehículos medianos (van) - diesel',
    name: 'Metano (CH4)',
    value: 0,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Productos - terrestre',
    nivel4: 'Vehículos medianos (van) - diesel',
    name: 'Óxido Nitroso (N2O)',
    value: 0.004,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Residuos - municipales',
    nivel4: '(disposición final)	Camión rígido promedio carga promedio 3 t',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.2074,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Residuos - municipales',
    nivel4: '(disposición final)	Camión rígido promedio carga promedio 3 t',
    name: 'Metano (CH4)',
    value: 0.0001,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Residuos - municipales',
    nivel4: '(disposición final)	Camión rígido promedio carga promedio 3 t',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0017,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Residuos - municipales',
    nivel4: '(disposición final)	Vehículos medianos (van) - diesel',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.5595,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Residuos - municipales',
    nivel4: '(disposición final)	Vehículos medianos (van) - diesel',
    name: 'Metano (CH4)',
    value: 0,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Residuos - municipales',
    nivel4: '(disposición final)	Vehículos medianos (van) - diesel',
    name: 'Óxido Nitroso (N2O)',
    value: 0.004,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Residuos - otros',
    nivel4: 'Camión rígido promedio carga promedio 3 t',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.2074,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Residuos - otros',
    nivel4: 'Camión rígido promedio carga promedio 3 t',
    name: 'Metano (CH4)',
    value: 0.0001,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Residuos - otros',
    nivel4: 'Camión rígido promedio carga promedio 3 t',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0017,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Residuos - otros',
    nivel4: 'Vehículos medianos (van) - diesel',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.5595,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Residuos - otros',
    nivel4: 'Vehículos medianos (van) - diesel',
    name: 'Metano (CH4)',
    value: 0,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Residuos - otros',
    nivel4: 'Vehículos medianos (van) - diesel',
    name: 'Óxido Nitroso (N2O)',
    value: 0.004,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Residuos - reciclaje',
    nivel4: 'Camión rígido promedio carga promedio 3 t',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.2074,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Residuos - reciclaje',
    nivel4: 'Camión rígido promedio carga promedio 3 t',
    name: 'Metano (CH4)',
    value: 0.0001,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Residuos - reciclaje',
    nivel4: 'Camión rígido promedio carga promedio 3 t',
    name: 'Óxido Nitroso (N2O)',
    value: 0.0017,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Residuos - reciclaje',
    nivel4: 'Vehículos medianos (van) - diesel',
    name: 'Dióxido de Carbono (CO2)',
    value: 0.5595,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Residuos - reciclaje',
    nivel4: 'Vehículos medianos (van) - diesel',
    name: 'Metano (CH4)',
    value: 0,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Transporte de carga',
    nivel3: 'Residuos - reciclaje',
    nivel4: 'Vehículos medianos (van) - diesel',
    name: 'Óxido Nitroso (N2O)',
    value: 0.004,
    measureUnit: 'kgCO2eq/t-km',
  },
  {
    nivel2: 'Tratamiento y/o disposición de residuos',
    nivel3: 'Reciclaje',
    nivel4: 'Aceite mineral',
    name: 'Dióxido de Carbono (CO2)',
    value: 21,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Tratamiento y/o disposición de residuos',
    nivel3: 'Reciclaje',
    nivel4: 'Agregados (Escombros)',
    name: '	Dióxido de Carbono (CO2)',
    value: 1,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Tratamiento y/o disposición de residuos',
    nivel3: 'Reciclaje',
    nivel4: 'Baterias (post-consumo no automotriz)',
    name: 'Dióxido de Carbono (CO2)',
    value: 65,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Tratamiento y/o disposición de residuos',
    nivel3: 'Reciclaje',
    nivel4: 'Construccion, Demolicion y Excavacion: Promedio',
    name: 'Dióxido de Carbono (CO2)',
    value: 1.37,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Tratamiento y/o disposición de residuos',
    nivel3: 'Reciclaje',
    nivel4: 'Equipos electricos y electronicos',
    name: 'Dióxido de Carbono (CO2)',
    value: 21,
    measureUnit: '	kgCO2eq/t',
  },
  {
    nivel2: 'Tratamiento y/o disposición de residuos',
    nivel3: 'Reciclaje',
    nivel4: 'Madera',
    name: 'Dióxido de Carbono (CO2) ',
    value: 21,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Tratamiento y/o disposición de residuos',
    nivel3: 'Reciclaje',
    nivel4: 'Metal: latas de aluminio y papel de aluminio',
    name: 'Dióxido de Carbono (CO2)',
    value: 21,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Tratamiento y/o disposición de residuos',
    nivel3: 'Reciclaje',
    nivel4: 'Metal: Chatarra Metalica',
    name: '	Dióxido de Carbono (CO2)',
    value: 21,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Tratamiento y/o disposición de residuos',
    nivel3: 'Reciclaje',
    nivel4: 'Neumaticos',
    name: 'Dióxido de Carbono (CO2)',
    value: 21,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Tratamiento y/o disposición de residuos',
    nivel3: 'Reciclaje',
    nivel4: 'Papel y cartón',
    name: 'Dióxido de Carbono (CO2)',
    value: 21,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Tratamiento y/o disposición de residuos',
    nivel3: 'Reciclaje',
    nivel4: 'Plasticos: HDPE',
    name: 'Dióxido de Carbono (CO2)',
    value: 21,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Tratamiento y/o disposición de residuos',
    nivel3: 'Reciclaje',
    nivel4: 'Plasticos: LDPE y LLDPE',
    name: 'Dióxido de Carbono (CO2)',
    value: 21,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Tratamiento y/o disposición de residuos',
    nivel3: 'Reciclaje',
    nivel4: 'Plasticos: PET',
    name: 'Dióxido de Carbono (CO2)',
    value: 21,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Tratamiento y/o disposición de residuos',
    nivel3: 'Reciclaje',
    nivel4: 'Plasticos: PP',
    name: 'Dióxido de Carbono (CO2)',
    value: 21,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Tratamiento y/o disposición de residuos',
    nivel3: 'Reciclaje',
    nivel4: 'Plasticos: Promedio de plasticos',
    name: 'Dióxido de Carbono (CO2)',
    value: 21,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Tratamiento y/o disposición de residuos',
    nivel3: 'Reciclaje',
    nivel4: 'Plasticos: PS',
    name: 'Dióxido de Carbono (CO2)',
    value: 21,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Tratamiento y/o disposición de residuos',
    nivel3: 'Reciclaje',
    nivel4: 'Plasticos: PVC',
    name: 'Dióxido de Carbono (CO2)',
    value: 21,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Tratamiento y/o disposición de residuos',
    nivel3: 'Reciclaje',
    nivel4: 'Textiles',
    name: 'Dióxido de Carbono (CO2)',
    value: 21,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Tratamiento y/o disposición de residuos',
    nivel3: 'Reciclaje',
    nivel4: 'Vidrio',
    name: 'Dióxido de Carbono (CO2)',
    value: 21,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Tratamiento y/o disposición de residuos',
    nivel3: 'Relleno sanitario',
    nivel4: 'Residuos comerciales e industriales',
    name: '	Dióxidode Carbono (CO2)',
    value: 199,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Tratamiento y/o disposición de residuos',
    nivel3: 'Relleno sanitario',
    nivel4: 'Residuos municipales',
    name: 'Dióxido de Carbono (CO2)',
    value: 421,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Tratamiento y/o disposición de residuos',
    nivel3: 'Vertedero',
    nivel4: 'Residuos comerciales e industriales',
    name: 'Dióxido de Carbono (CO2)',
    value: 199,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Tratamiento y/o disposición de residuos',
    nivel3: 'Vertedero',
    nivel4: 'Residuos municipales',
    name: 'Dióxido de Carbono (CO2)',
    value: 421,
    measureUnit: 'kgCO2eq/t',
  },
  {
    nivel2: 'Tratamiento y/o disposición de residuos',
    nivel3: 'Compostaje',
    nivel4: 'Residuos orgánicos',
    name: 'Dióxido de Carbono (CO2)',
    value: 6,
    measureUnit: 'kgCO2eq/t',
  },
]
